// User authorization
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_INCOMPLETE = 'AUTH_INCOMPLETE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// User view
export const USER_REQUEST = 'USER_REQUEST';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const TOGGLE_SAVE_ADDRESS = 'TOGGLE_SAVE_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';

// Ticker
export const GET_EXCHANGE_RATE_REQUEST = 'GET_EXCHANGE_RATE_REQUEST';
export const GET_EXCHANGE_RATE_SUCCESS = 'GET_EXCHANGE_RATE_SUCCESS';
export const GET_EXCHANGE_RATE_FAILURE = 'GET_EXCHANGE_RATE_FAILURE';

// Categories
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

// Search results
export const GET_SEARCH_RESULTS_REQUEST = 'GET_SEARCH_RESULTS_REQUEST';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_FAILURE = 'GET_SEARCH_RESULTS_FAILURE';
